added basic ssh host with existing key example
abklabs/pulumi-svmkit pull request #30
Opened 2024-10-23 22:59 UTC by mfhughes

super basic single host ssh functionality example done for/with alexander.

2024-10-24 06:55 UTC, kespinola requested changes
A few notes but excited to have you as our first outside contributor!

2024-10-24 06:55 UTC, kespinola commented on examples/ssh-host-agave-validator-python/__main__.py
> +-----END OPENSSH PRIVATE KEY-----"""
Can you look at moving this to the Pulumi config and add a simple readme that describes encrypting the ssh key with pulumi?

2024-10-24 06:55 UTC, kespinola commented on examples/ssh-host-agave-validator-python/__main__.py
> +#    opts=pulumi.ResourceOptions(depends_on=[instance])
```suggestion
```

2024-10-27 19:24 UTC, alexanderguy approved these changes
LGTM; thank you for the contribution.

2024-10-27 19:24 UTC, merged